### PR TITLE
fix(styled-jsx/index): Injecting style in first child if root is non element

### LINKED ISSUE #245: styled-jsx should be injected in the first element node
Currently the styled-jsx plugin assumes the top level node inside the component is of type `element`, but as of #182, we can have any node type as the root node. The plugin should traverse the tree until the first element is found and place the <style> tag there

### PR DESCRIPTION
**Pull request by JayaKrishnaNamburu**
fixes #245

### CODE REVIEW

**Comment by JayaKrishnaNamburu** [comment]
Any idea why the tests are breaking, in my local all tests are passing
Screenshot 2019-06-11 at 2 25 30 PM

File: packages/teleport-plugin-react-styled-jsx/src/index.ts [hunk 1]
```diff
@@ -59,13 +59,15 @@ export const createPlugin: ComponentPluginFactory<StyledJSXConfig> = (config) =>
...
-    const rootJSXNode = jsxNodesLookup[(node.content as UIDLElement).key] // TODO: Check for other types
-
     // We have the ability to insert the tag into the existig JSX structure, or do something else with it.
     // Here we take the JSX <style> tag and we insert it as the last child of the JSX structure
     // inside the React Component
-    rootJSXNode.children.push(jsxASTNodeReference)
+    const rootNodeKey = (node.content as UIDLElement).key
+    const rootJSXNode = rootNodeKey
+      ? jsxNodesLookup[rootNodeKey]
+      : jsxNodesLookup[Object.keys(jsxNodesLookup)[0]]
```
Comment (alexnm) [inline packages/teleport-plugin-react-styled-jsx/src/index.ts]: this is a neat trick, but I wouldn't count on the fact that the object keys are in the right order. it also might be a bit harder for someone to understand. my proposal is to make a utility function that gives you the first element node in a given UIDL structure. might be useful in other cases in the future as well

Comment (JayaKrishnaNamburu) [reply packages/teleport-plugin-react-styled-jsx/src/index.ts]: Sure, will change this 👍

File: packages/teleport-plugin-react-styled-jsx/src/index.ts [hunk 2]
```diff
@@ -59,13 +59,19 @@ export const createPlugin: ComponentPluginFactory<StyledJSXConfig> = (config) =>
     }
 
     const jsxASTNodeReference = generateStyledJSXTag(styleJSXString.join('\n'))
-    const rootJSXNode = jsxNodesLookup[(node.content as UIDLElement).key] // TODO: Check for other types
-
     // We have the ability to insert the tag into the existig JSX structure, or do something else with it.
     // Here we take the JSX <style> tag and we insert it as the last child of the JSX structure
     // inside the React Component
-    rootJSXNode.children.push(jsxASTNodeReference)
+    let rootJSXNode
```
Comment (alexnm) [inline packages/teleport-plugin-react-styled-jsx/src/index.ts]: It's easier to compute the rootJSXNode as the result of `traverseUIDLForRootElmNode` then you don't need to do the cast here nor the if statement

File: packages/teleport-plugin-react-styled-jsx/src/index.ts [hunk 3]
```diff
@@ -59,13 +59,19 @@ export const createPlugin: ComponentPluginFactory<StyledJSXConfig> = (config) =>
...
+    const rootNodeKey = (node.content as UIDLElement).key
+    if (rootNodeKey) {
```
Comment (alexnm) [inline packages/teleport-plugin-react-styled-jsx/src/index.ts]: only the else code is needed if actually, you don't need to check if the root is a UIDLElement as the function will check it

File: packages/teleport-shared/src/utils/uidl-utils.ts [hunk 4]
```diff
@@ -424,3 +424,16 @@ export const transformAttributesAssignmentsToJson = (
 
   return newStyleObject
 }
+
+export const traverseUIDLForRootElmNode = (node) => {
```
Comment (alexnm) [inline packages/teleport-shared/src/utils/uidl-utils.ts]: I would name this: `findFirstElementNode` because the traverse functions don't return something necessarily, they call a function on the node. in this case you are returning a specific node.

Comment (alexnm) [reply packages/teleport-shared/src/utils/uidl-utils.ts]: also, add the typing for the `node`

File: packages/teleport-shared/src/utils/uidl-utils.ts [hunk 5]
```diff
@@ -424,3 +424,16 @@ export const transformAttributesAssignmentsToJson = (
...
+  if (node && node.type) {
```
Comment (alexnm) [inline packages/teleport-shared/src/utils/uidl-utils.ts]: why is this test needed?

File: packages/teleport-shared/src/utils/uidl-utils.ts [hunk 6]
```diff
@@ -424,3 +424,16 @@ export const transformAttributesAssignmentsToJson = (
...
+    if (node.type === 'element') {
```
Comment (alexnm) [inline packages/teleport-shared/src/utils/uidl-utils.ts]: this should be replaced with a switch like function:
 - case element -> return node
 - case static/dynamic throw error
 - case conditional/repeat/slot -> return recursive call

File: packages/teleport-shared/src/utils/uidl-utils.ts (hunk 5 above)
Comment (JayaKrishnaNamburu) [reply packages/teleport-shared/src/utils/uidl-utils.ts]: Not needed actually, I tried too many UIDL's and ended up doing this 😅 will remove 👍

File: packages/teleport-plugin-react-styled-jsx/src/index.ts (hunk 3 above)
Comment (JayaKrishnaNamburu) [reply packages/teleport-plugin-react-styled-jsx/src/index.ts]: Yeah right! I wonder how I missed this 😅

File: packages/teleport-shared/src/utils/uidl-utils.ts (hunk 5 above)
Comment (JayaKrishnaNamburu) [reply packages/teleport-shared/src/utils/uidl-utils.ts]: Yeah, I was doing this for the case of static and dynamic. I will throw an error from now on.
