### PR TITLE
fix(plugin-styles): Fix generation of empty styles

### LINKED ISSUE #288: Empty style block generates empty style code
The `React` style plugins all generate some sort of empty style object/component even though no keys are defined inside the `style` block.

Sample UIDL:
```json
{
  "name": "Simple Component",
  "propDefinitions": {
    "title": {
      "type": "string",
      "defaultValue": "Hello",
      "isRequired": true
    }
  },
  "node": {
    "type": "element",
    "content": {
      "elementType": "container",
      "style": {
        
      },
      "children": [
        {
          "type": "element",
          "content": {
            "elementType": "text",
            "children": [
              {
                "type": "dynamic",
                "content": {
                  "referenceType": "prop",
                  "id": "title"
                }
              },
              {
                "type": "static",
                "content": "World!"
              }
            ]
          }
        }
      ]
    }
  }
}
```

This can be easily tested in the repl: https://repl.teleporthq.io/

### PR DESCRIPTION
**Pull request by JayaKrishnaNamburu**
Fixes #288

### CODE REVIEW

File: packages/teleport-plugin-react-css-modules/src/index.ts [hunk 1]
```diff
@@ -66,7 +66,7 @@ export const createPlugin: ComponentPluginFactory<ReactCSSModulesConfig> = (conf
 
     traverseElements(uidl.node, (element) => {
       const { style, key } = element
-      if (style) {
+      if (style && Object.keys(style).length > 0) {
```
Comment (alexnm) [inline packages/teleport-plugin-react-css-modules/src/index.ts]: can you check how I solved this in the stencil-css plugin which is still experimental? I think it's better to check both for inline styles as well as for the external styles:

https://github.com/teleporthq/teleport-code-generators/pull/308/files#diff-499a2b85fe4af0f3722b2a33b09ccad4R47

without this, if you have a dynamic style with css-modules, the class is still generated

File: packages/teleport-plugin-vue-css/src/index.ts [hunk 2]
```diff
@@ -44,7 +44,7 @@ export const createPlugin: ComponentPluginFactory<VueStyleChunkConfig> = (config
     traverseElements(node, (element) => {
       const { style, key } = element
 
-      if (style) {
+      if (style && Object.keys(style).length > 0) {
```
Comment (alexnm) [inline packages/teleport-plugin-vue-css/src/index.ts]: the same comment here as for css-modules. when splitting dynamic and static styles, we should check the separate objects so that we only generate what is actually needed

File: packages/teleport-plugin-react-css-modules/src/index.ts (hunk 1 above)
Comment (JayaKrishnaNamburu) [reply packages/teleport-plugin-react-css-modules/src/index.ts]: Sure
