### PR TITLE
Fix for #148

### LINKED ISSUE #148: React dynamic children don't add props.NAME_OF_PROP
this UIDL child form a `node.children[]`
```json
 {
     "type": "dynamic",
     "content": {
          "referenceType": "prop",
         "id": "title"
    }
}
```
produces the following sytanx.
```jsx
<span>
        Hello World!
        {title}
</span>
```

The problem is that title needs to be prefixed by `props.` like

```jsx
<span>
        Hello World!
        {props.title}
</span>
```
We should add a test for this as well.

### PR DESCRIPTION
**Pull request by vladnicula**
Fix #148

### CODE REVIEW

File: src/plugins/teleport-plugin-react-base-component/utils.ts [hunk 1]
```diff
@@ -334,8 +334,11 @@ const makeRepeatStructureWithMap = (
   )
 }
 
-const makeDynamicValueExpression = (identifier: string, t = types) => {
-  return t.jsxExpressionContainer(t.identifier(identifier))
+const makeDynamicValueExpression = (identifier: UIDLDynamicReference, t = types) => {
+  const prefix = getReactVarNameForDynamicReference(identifier)
```
Comment (alexnm) [inline src/plugins/teleport-plugin-react-base-component/utils.ts]: does this work if prefix is empty?
